<!doctype html>
<html lang="en">
<head>
    <title>Поиск</title>
</head>
<body>
<div>
    <h3>Поиск</h3>
    <form action="/search-request" method="POST">
            <div>
                <div>
                    <h3>Поисковая строка</h3>
                </div>
                <input type="text" placeholder="Что ищем ?" name="searchWords">
            </div>
            <div>
                <div>
                    <button type="submit"> Искать</button>
                </div>
            </div>
        </div>
    </form>
</div>
</body>
</html>